### ISSUE TITLE
Layout problem on iPhone XR

### ISSUE THREAD

**Issue by dkwiebe** [dkwiebe/CloudVeil-iOS#11]
I think this black bar is only a problem on brand new iOS devices.   I don't have one to test on but can you test in the simulator?

![image](https://user-images.githubusercontent.com/1034679/47809728-35af7180-dd07-11e8-87cf-c88b5ed0093c.png)

**Comment by thetmtech** [comment]
This doesn't look very good with the rounded corners, the mic and attachment button are about running off the screen. 
The latest version of Telegram has the message field raised up on the XR.
![img_0003](https://user-images.githubusercontent.com/26845997/50044151-891e1a80-003c-11e9-8551-816df1bc6580.jpg)
.

**Comment by patriciy** [comment]
Issue in official repo is more than year old
https://github.com/peter-iakovlev/Telegram/issues/182

**Comment by thetmtech** [comment]
This is fixed in the latest builds.
