### ISSUE TITLE
Able to search for gifs

### ISSUE THREAD

**Issue by montesound** [dkwiebe/CloudVeil-iOS#13]
Open a chat, click the emoji button, then click GIF, and then search.
![screenshot_4](https://user-images.githubusercontent.com/7513273/49111806-c6219900-f256-11e8-8036-09d7ee2ecbc3.png)

**Comment by patriciy** [comment]
Gif search is 3rd party software (Swift Keyboard) so we can't do anything to block it. 
We decided to turn off gif autoplay for now as it's done for Android
