### ISSUE TITLE
Share link is broken

### ISSUE THREAD

**Issue by thetmtech** [dkwiebe/CloudVeil-iOS#3]
The share sheet is freezing when opening CloudVeil Messenger. Open Photos and try sharing a photo using CloudVeil Messenger.

**Comment by thetmtech** [comment]
Looks like a reinstall fixed it for now on this device. Have one more with the issue yet. Will try reinstalling on it as well.

**Comment by dkwiebe** [comment]
@tysonkcv Is this still an issue?
